### ISSUE TITLE
Crash when using .csv files containing empty string

### ISSUE THREAD

**Issue by phspo** [saezlab/cytocopter#7]
Using the data provided here: http://nbviewer.jupyter.org/github/saezlab/CellNOptR/blob/gh-pages/public/MD-LiverMSB2009.csv the software crashes with the following error:

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:592) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:?]
	at uk.ac.ebi.cytocopter.internal.mahdimidas.CNO.valueCuesAsInteger(CNO.java:428) ~[?:?]
	at uk.ac.ebi.cytocopter.internal.mahdiplotting.ContainerPanel.initializeData(ContainerPanel.java:68) ~[?:?]
	at uk.ac.ebi.cytocopter.internal.mahdiplotting.ContainerPanel.<init>(ContainerPanel.java:45) ~[?:?]
	at uk.ac.ebi.cytocopter.internal.cellnoptr.tasks.PreprocessTask.run(PreprocessTask.java:158) ~[?:?]
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321) ~[87:org.cytoscape.work-swing-impl:3.7.2]
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352) [87:org.cytoscape.work-swing-impl:3.7.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at uk.ac.ebi.cytocopter.internal.mahdimidas.CNO.valueCuesAsInteger(CNO.java:428)
	at uk.ac.ebi.cytocopter.internal.mahdiplotting.ContainerPanel.initializeData(ContainerPanel.java:68)
	at uk.ac.ebi.cytocopter.internal.mahdiplotting.ContainerPanel.<init>(ContainerPanel.java:45)
	at uk.ac.ebi.cytocopter.internal.cellnoptr.tasks.PreprocessTask.run(PreprocessTask.java:158)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

This can be fixed by entering 0s for every empty cell

**Comment by gabora** [comment]
Hi,
thanks for the report. 
Indeed, a proper MIDAS file cannot have empty cells. 
In the Cytocopter there is a limited number of checkings for the correct formating of inputs.
